# Generated by Django 4.2.4 on 2023-09-13 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_alter_index_page_up_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pixel',
            field=models.CharField(default='', max_length=2000),
        ),
    ]
