# Generated by Django 4.2.4 on 2023-09-13 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0024_product_pixel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pixel',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
